name: Publish MacOS
on:
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Packages
        run: yarn install
      - name: Rebuild Native Modules
        run: npx electron-rebuild
      - name: Get Urbit Binaries
        run: ./get-urbit.sh
      - name: Add MacOS certs
        run: chmod +x add-osx-cert.sh && ./add-osx-cert.sh
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
      - name: Build & Publish
        run: |
          yarn run publish --arch x64,arm64
        env:
          APPLE_ID: ${{secrets.APPLE_ID}}
          APPLE_ID_PASSWORD: ${{secrets.APPLE_ID_PASSWORD}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}