name: Publish Windows
on:
  push:
    branches: [ main, "1.9-fixes" ]
jobs:
  publish:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Packages
        run: |
          yarn config set network-timeout 600000
          yarn install
      - name: Rebuild Native Modules
        run: npx electron-rebuild
      - name: Get Urbit Binaries
        run: get-urbit
        shell: cmd
      - name: Build & Publish
        run: |
          yarn run publish
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}