name: Release Linux
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install flatpak deps
        run: |
          sudo apt-get install flatpak -y
          sudo apt-get install flatpak-builder -y
          sudo apt-get install elfutils -y
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install flathub org.freedesktop.Platform/x86_64/19.08 org.freedesktop.Sdk/x86_64/19.08 org.electronjs.Electron2.BaseApp/x86_64/stable -y
      - name: Setup Snapcraft
        run: |
          sudo chown -R $USER:$USER /home/runner
          sudo snap install snapcraft --classic
          echo "$SNAP_TOKEN" | snapcraft login --with -   
        env:
          SNAP_TOKEN: ${{secrets.SNAP_TOKEN}}
      - name: Install Packages
        run: yarn install
      - name: Rebuild Native Modules
        run: npx electron-rebuild
      - name: Get Urbit Binaries
        run: ./get-urbit.sh
      - name: Build & Publish
        run: |
          yarn run publish
          snapcraft upload --release=stable out/make/*.snap
        env:
          SNAPCRAFT_BUILD_ENVIRONMENT: host
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}